export { default as DashboardIcon }    from "./dashboard.svg?react";
export { default as CounselorIcon }   from "./counselor.svg?react";
export { default as AppointmentsIcon } from "./appointments.svg?react";
export { default as PeopleIcon }       from "./people.svg?react";
export { default as BooksIcon }        from "./books.svg?react";
export { default as ScheduleIcon }     from "./Schedule.svg?react";
export { default as SettingsIcon }     from "./Settings.svg?react";
export { default as LogoutIcon }       from "./logout.svg?react";
export { default as MenuIcon }         from "./MenuIcon.svg?react";
export { default as ScheduleIcon1 } from "./schedule1.svg?react";
export { default as ScheduleIcon2 } from "./schedule2.svg?react";
export { default as ScheduleIcon3 } from "./schedule3.svg?react";
export { default as CancelIcon }     from "./Cancel.svg?react";
export { default as CopyIcon }     from "./Copy.svg?react";
export { default as AddIcon }     from "./Add.svg?react";
export { default as CameraIcon }         from "./Camera.svg?react";
export { default as PdfIcon }         from "./pdf.svg?react";
export {default as TopUpIcon} from "./topup.svg?react";
export {default as WithdrawIcon} from "./withdraw.svg?react";
export {default as TimerIcon} from "./timer.svg?react";
export {default as UptrendIcon} from "./uptrend.svg?react";
export {default as ChevronLeftIcon} from "./chevronleft.svg?react";
export {default as MeetingIcon} from "./meeting.svg?react";
export {default as ChatIcon} from "./chat.svg?react";
export {default as RescheduleIcon} from "./reschedule.svg?react";
export {default as UserIcon} from "./user.svg?react";
export { default as ChevronDownIcon } from "./ChevronDown.svg?react";
export { default as TransactionIcon } from "./transaction.svg?react";